apiVersion: acid.zalan.do/v1
kind: postgresql
metadata:
  name: example-database
  namespace: default
spec:
  enableLogicalBackup: true
  numberOfInstances: 2
  postgresql:
    version: '16'
  teamId: kratix
  users:
    team-a:
    - superuser
    - createdb
  volume:
    size: 1Gi
