apiVersion: awx.ansible.com/v1beta1
kind: AWX
metadata:
  name: awx
  namespace: awx
spec:
  service_type: LoadBalancer
  loadbalancer_ip: 192.168.20.51
  admin_user: admin
  admin_password_secret: awx-admin-password
  postgres_storage_requirements:
    requests:
      storage: 8Gi
  postgres_security_context:
    runAsUser: 26
    fsGroup: 26
